In [1]:
import pandas as pd
import numpy as np
from scipy.spatial import distance
from sklearn.metrics import accuracy_score
from sklearn.decomposition import PCA
import matplotlib.pyplot as plt
#locate files from computer

In [2]:
#Import anmd merger for demographics get the mean
#af = pd.read_csv('DCmergedfile.csv')
af = pd.read_csv('DCfileswithhouse.csv')
#mean for demographics 
aff = af.groupby(['PERSON_ID']).mean()
aff

/var/folders/fs/02s140qd6n97_sck15lvgycm0000gn/T/ipykernel_703/2965195760.py:3: DtypeWarning: Columns (27,28,30,32,55,58) have mixed types. Specify dtype option on import or set low_memory=False.
  af = pd.read_csv('DCfileswithhouse.csv')

,Unnamed: 0.1,Unnamed: 0,HOUSEHOLD_ID,PERSNO,TRIPID,Dwelltime,TRIPNO,O_PURPOSE,O_ACTIVITY,MPO_O_ACTIVITY,...,MPO_HH_INCOME_BROAD,TDATE_DOW,HHTRIPS,PACKAGE_DELIVERED,FOOD_DELIVERED,SERVICE_DELIVERED,WTHHFIN,HOME_OWNERSHIP_IMP,HH_INCOME_DETAILED_IMP,NUMDISABILITIES_IMP
PERSON_ID,,,,,,,,,,,,,,,,,,,,,
14000027101,2.0,2.0,140000271.0,1.0,1.400000e+12,-29.200000,3.0,3.000000,3.000000,-9.0,...,-9.0,1.0,7.0,0.0,0.0,0.0,136.460113,-9.0,-9.0,-9.0
14000027103,5.5,5.5,140000271.0,3.0,1.400000e+12,-78.000000,1.5,50.000000,1.500000,-9.0,...,-9.0,1.0,7.0,0.0,0.0,0.0,136.460113,-9.0,-9.0,-9.0
14000028001,9.0,9.0,140000280.0,1.0,1.400000e+12,25.600000,3.0,3.600000,4.400000,-9.0,...,-9.0,1.0,5.0,0.0,0.0,0.0,131.745870,-9.0,-9.0,-9.0
14000028401,14.0,14.0,140000284.0,1.0,1.400000e+12,-71.000000,3.0,7.000000,9.200000,-9.0,...,-9.0,5.0,5.0,0.0,0.0,0.0,91.688043,-9.0,-9.0,-9.0
14000029101,18.0,18.0,140000291.0,1.0,1.400000e+12,138.333333,2.0,4.333333,4.000000,-9.0,...,-9.0,2.0,5.0,1.0,0.0,0.0,88.698225,-9.0,-9.0,-9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18025693601,126856.0,126856.0,180256936.0,1.0,1.800000e+12,-2.000000,3.0,4.800000,6.600000,9.6,...,2.0,3.0,5.0,0.0,0.0,0.0,101.000000,0.0,1.0,1.0
18025694001,126861.0,126861.0,180256940.0,1.0,1.800000e+12,-31.000000,3.0,4.400000,6.800000,206.2,...,2.0,1.0,10.0,0.0,0.0,1.0,139.000000,0.0,0.0,0.0
18025694002,126866.0,126866.0,180256940.0,2.0,1.800000e+12,91.000000,3.0,4.800000,5.200000,8.8,...,2.0,1.0,10.0,0.0,0.0,1.0,139.000000,0.0,0.0,0.0
18025694101,126869.5,126869.5,180256941.0,1.0,1.800000e+12,-387.500000,1.5,2.500000,4.000000,6.5,...,2.0,5.0,5.0,0.0,0.0,0.0,157.000000,0.0,1.0,0.0
18025694102,126872.0,126872.0,180256941.0,2.0,1.800000e+12,-165.000000,2.0,2.333333,2.666667,5.0,...,2.0,5.0,5.0,0.0,0.0,0.0,157.000000,0.0,1.0,0.0

In [3]:
my_list = list(aff)
my_list

['Unnamed: 0.1',
 'Unnamed: 0',
 'HOUSEHOLD_ID',
 'PERSNO',
 'TRIPID',
 'Dwelltime',
 'TRIPNO',
 'O_PURPOSE',
 'O_ACTIVITY',
 'MPO_O_ACTIVITY',
 'O_STATE_FIPS',
 'O_STATE_COUNTY_FIPS',
 'O_TRACT_FIPS',
 'O_TPB_TAZ',
 'O_BMC_TAZ',
 'D_PURPOSE',
 'D_ACTIVITY',
 'MPO_D_ACTIVITY',
 'D_STATE_FIPS',
 'D_STATE_COUNTY_FIPS',
 'D_TRACT_FIPS',
 'D_TPB_TAZ',
 'D_BMC_TAZ',
 'TRAVEL_MODE',
 'TRANSIT_ACCESS_MODE',
 'TRANSIT_EGRESS_MODE',
 'TRAVELERS_TOTAL',
 'TRAVELERS_HH',
 'TRAVELERS_NONHH',
 'HH_MEMBER1',
 'HH_MEMBER2',
 'HH_MEMBER3',
 'HH_MEMBER4',
 'HH_MEMBER5',
 'HH_MEMBER6',
 'HH_MEMBER7',
 'HH_MEMBER8',
 'MODE_HH_VEHICLE',
 'MPO_MODE_OTHER_VEHICLE',
 'VEHICLE_OCCUPANCY',
 'PARK_LOC',
 'MPO_PARK_LOC',
 'PARK_PAY',
 'MPO_PARK_PAY',
 'SUBWAY_USED',
 'SUBWAY_PAY',
 'SUBWAY_STATION_BOARD',
 'SUBWAY_ACCESS_MODE',
 'SUBWAY_STATION_EXIT',
 'SUBWAY_EGRESS_MODE',
 'HOV_USED',
 'TOLL_ROAD_USED',
 'DISTANCE',
 'REPORTED_TRAVEL_TIME',
 'WTTRDFIN',
 'WWM_WTTRDFIN',
 'HOUSEHOLD_ID_y',
 'AGE',
 'AGE_GROUP',
 'GENDER',
 'RACEETHNICITY',
 'MPO_RACEETHNICITY',
 'RACEETHNICITY_HISPANIC',
 'MPO_RACEETHNICITY_HISPANIC',
 'LICENSE',
 'DISABILITY',
 'SMARTPHONE',
 'EMPLOYMENT_STATUS',
 'MPO_EMPLOYMENT_STATUS',
 'MPO_UNEMPLOYMENT_STATUS',
 'JOBS_COUNT',
 'MPO_J1_EMPLOYER_TYPE',
 'J1_WORKPLACE_LOC',
 'WORK_STATE_FIPS',
 'WORK_STATE_COUNTY_FIPS',
 'WORK_TRACT_FIPS',
 'WORK_TPB_TAZ',
 'WORK_BMC_TAZ',
 'J1_COMMUTE_FREQ',
 'J1_COMMUTE_MODE',
 'MPO_J1_COMMUTE_MODE',
 'J1_TELECOMMUTE',
 'MPO_J1_TELECOMMUTE',
 'J1_TELECOMMUTE_DAYS',
 'MPO_J1_TELECOMMUTE_DAYS',
 'J1_BENEFITS_FREE_PARKING',
 'J1_BENEFITS_PARKING',
 'J1_BENEFITS_TRANSIT',
 'J1_BENEFITS_CARPOOL',
 'J1_BENEFITS_WALKING_BIKING',
 'J1_BENEFITS_EV_CHARGING',
 'J1_BENEFITS_BICYCLE_PARKING',
 'J1_BENEFITS_NONE',
 'STUDENT_STATUS',
 'SCHOOL_TYPE',
 'MPO_SCHOOL_TYPE',
 'SCHOOL_STATE_FIPS',
 'SCHOOL_STATE_COUNTY_FIPS',
 'SCHOOL_TRACT_FIPS',
 'SCHOOL_TPB_TAZ',
 'SCHOOL_BMC_TAZ',
 'SCHOOL_FREQ',
 'SCHOOL_MODE',
 'MPO_SCHOOL_MODE',
 'VOLUNTEER_STATUS',
 'TRIPS_YESNO',
 'NO_TRAVEL',
 'MPO_NO_TRAVEL',
 'TD_PAIDPARK',
 'TD_HOV',
 'TD_TOLL',
 'TD_TELECOMMUTE_TIME',
 'MPO_TD_TELECOMMUTE_TIME',
 'TD_SHOP_TIME',
 'MPO_TD_SHOP_TIME',
 'PERSON_TRIPCOUNT',
 'WALK_BIKE_LOOP_TRIPS',
 'WTPERFIN',
 'WWM_WTPERFIN',
 'AGE_IMP',
 'GENDER_IMP',
 'RACEETHNICITY_IMP',
 'MPO_RACEETHNICITY_IMP',
 'DISABILITY_IMP',
 'IN_TPB',
 'IN_BMC',
 'HOME_STATE_FIPS',
 'AREA_TYPE',
 'HOME_STATE_COUNTY_FIPS',
 'HOME_TRACT_FIPS',
 'HOME_TPB_TAZ',
 'HOME_BMC_TAZ',
 'HOME_TYPE',
 'MPO_HOME_TYPE',
 'HOME_OWNERSHIP',
 'MPO_HOME_OWNERSHIP',
 'HHSIZE',
 'NUMSTUDENTS',
 'NUMDRIVERS',
 'NUMWORKERS',
 'NUMDISABILITIES',
 'NUMVEHICLE',
 'NUMVEHICLE_TRANSPONDER',
 'NUMBICYCLE',
 'HH_INCOME_DETAILED',
 'MPO_HH_INCOME_DETAILED',
 'HH_INCOME_BROAD',
 'MPO_HH_INCOME_BROAD',
 'TDATE_DOW',
 'HHTRIPS',
 'PACKAGE_DELIVERED',
 'FOOD_DELIVERED',
 'SERVICE_DELIVERED',
 'WTHHFIN',
 'HOME_OWNERSHIP_IMP',
 'HH_INCOME_DETAILED_IMP',
 'NUMDISABILITIES_IMP']

In [4]:
#df1["WHYTO"].replace({1: 'Home', 2: 'Home', 3:'Stop', 4:'Stop', 5: 'Stop', 6:'Stop', 7:'Stop', 8:'Stop', 9:'Stop', 10:'Stop', 11:'Stop', 12:'Stop',13:'Stop',14:'Stop',15:'Stop',16:'Stop',17:'Stop',18:'Stop',19:'Stop',97:'Stop',-7 :'Stop', -8 : 'Stop', 97:'Stop',-9:'Stop'}, inplace=True)
#df1["D_PURPOSE"].replace({1: 'Home', 2: 'Work', 3:'Work', 4:'Shop', 7:'School', 8:'School', 9:'Other', 11:'Other',13:'Other',16:'Publictransit',17:'Publictransit',19:'Airport',77:'Other',99 :'Other',-9:'Other'}, inplace=True)
aff["RACEETHNICITY"].replace({1:"Hispanic", 2: "Black", 3:'Asian', 4:'White',5:'Others', -9:'Others'},  inplace = True)
#df["TRAVEL_MODE"].replace({1: 'Walk', 2: 'Bike', 3:'Bike', 4:'Car', 5:'Car', 6:'School bus', 7:'rail', 8:'Bus', 9:'Bus',10:'Para transit',11:'Taxi',12:'Taxi',13:'Air',14:'Water',15:'Others'}, inplace=True)
aff["TRAVEL_MODE"].replace({1: 'Walk', 2: 'Bike', 3:'Bike', 4:'Private car', 5:'Private car', 6:'School bus', 7:'Public transit', 8:'Public transit', 9:'Rideshare/Private Bus',10:'Rideshare/Private Bus',11:'Rideshare/Private Bus',12:'Rideshare/Private Bus',13:'Others',14:'Others',15:'Others'}, inplace=True)
aff["LICENSE"].replace({1: 'With License', 2: 'No License',-9:'No response'}, inplace=True)
aff["DISABILITY"].replace({1: 'Disabled', 2: 'Not disabled',-9:'No response'}, inplace=True)
aff["EMPLOYMENT_STATUS"].replace({0: 'Employed',1: 'Retired', 2: 'Employed', 3:'Unemployed',4:'Unemployed', 5:'Unemployed', 6:'Student',7:'Unemployed',-9:'Unemployed'}, inplace=True)
aff["GENDER"].replace({1: 'Female', 2: 'Male',-9:'No response'}, inplace=True)


aff

,Unnamed: 0.1,Unnamed: 0,HOUSEHOLD_ID,PERSNO,TRIPID,Dwelltime,TRIPNO,O_PURPOSE,O_ACTIVITY,MPO_O_ACTIVITY,...,MPO_HH_INCOME_BROAD,TDATE_DOW,HHTRIPS,PACKAGE_DELIVERED,FOOD_DELIVERED,SERVICE_DELIVERED,WTHHFIN,HOME_OWNERSHIP_IMP,HH_INCOME_DETAILED_IMP,NUMDISABILITIES_IMP
PERSON_ID,,,,,,,,,,,,,,,,,,,,,
14000027101,2.0,2.0,140000271.0,1.0,1.400000e+12,-29.200000,3.0,3.000000,3.000000,-9.0,...,-9.0,1.0,7.0,0.0,0.0,0.0,136.460113,-9.0,-9.0,-9.0
14000027103,5.5,5.5,140000271.0,3.0,1.400000e+12,-78.000000,1.5,50.000000,1.500000,-9.0,...,-9.0,1.0,7.0,0.0,0.0,0.0,136.460113,-9.0,-9.0,-9.0
14000028001,9.0,9.0,140000280.0,1.0,1.400000e+12,25.600000,3.0,3.600000,4.400000,-9.0,...,-9.0,1.0,5.0,0.0,0.0,0.0,131.745870,-9.0,-9.0,-9.0
14000028401,14.0,14.0,140000284.0,1.0,1.400000e+12,-71.000000,3.0,7.000000,9.200000,-9.0,...,-9.0,5.0,5.0,0.0,0.0,0.0,91.688043,-9.0,-9.0,-9.0
14000029101,18.0,18.0,140000291.0,1.0,1.400000e+12,138.333333,2.0,4.333333,4.000000,-9.0,...,-9.0,2.0,5.0,1.0,0.0,0.0,88.698225,-9.0,-9.0,-9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18025693601,126856.0,126856.0,180256936.0,1.0,1.800000e+12,-2.000000,3.0,4.800000,6.600000,9.6,...,2.0,3.0,5.0,0.0,0.0,0.0,101.000000,0.0,1.0,1.0
18025694001,126861.0,126861.0,180256940.0,1.0,1.800000e+12,-31.000000,3.0,4.400000,6.800000,206.2,...,2.0,1.0,10.0,0.0,0.0,1.0,139.000000,0.0,0.0,0.0
18025694002,126866.0,126866.0,180256940.0,2.0,1.800000e+12,91.000000,3.0,4.800000,5.200000,8.8,...,2.0,1.0,10.0,0.0,0.0,1.0,139.000000,0.0,0.0,0.0
18025694101,126869.5,126869.5,180256941.0,1.0,1.800000e+12,-387.500000,1.5,2.500000,4.000000,6.5,...,2.0,5.0,5.0,0.0,0.0,0.0,157.000000,0.0,1.0,0.0
18025694102,126872.0,126872.0,180256941.0,2.0,1.800000e+12,-165.000000,2.0,2.333333,2.666667,5.0,...,2.0,5.0,5.0,0.0,0.0,0.0,157.000000,0.0,1.0,0.0

In [5]:
category = pd.cut(aff.AGE,bins=[0,5,17,65,99],labels=['Toddler/baby','Child','Adult','Elderly'])
aff.insert(5,'Ageclass',category)
#categorization of variables
category = pd.cut(aff.HH_INCOME_DETAILED,bins=[0,2,6,90,10000],labels=['Poverty','Middleclass','Rich','Refused'])
aff.insert(5,'Incomeclass',category)
aff

,Unnamed: 0.1,Unnamed: 0,HOUSEHOLD_ID,PERSNO,TRIPID,Incomeclass,Ageclass,Dwelltime,TRIPNO,O_PURPOSE,...,MPO_HH_INCOME_BROAD,TDATE_DOW,HHTRIPS,PACKAGE_DELIVERED,FOOD_DELIVERED,SERVICE_DELIVERED,WTHHFIN,HOME_OWNERSHIP_IMP,HH_INCOME_DETAILED_IMP,NUMDISABILITIES_IMP
PERSON_ID,,,,,,,,,,,,,,,,,,,,,
14000027101,2.0,2.0,140000271.0,1.0,1.400000e+12,Rich,Adult,-29.200000,3.0,3.000000,...,-9.0,1.0,7.0,0.0,0.0,0.0,136.460113,-9.0,-9.0,-9.0
14000027103,5.5,5.5,140000271.0,3.0,1.400000e+12,Rich,Adult,-78.000000,1.5,50.000000,...,-9.0,1.0,7.0,0.0,0.0,0.0,136.460113,-9.0,-9.0,-9.0
14000028001,9.0,9.0,140000280.0,1.0,1.400000e+12,Rich,Elderly,25.600000,3.0,3.600000,...,-9.0,1.0,5.0,0.0,0.0,0.0,131.745870,-9.0,-9.0,-9.0
14000028401,14.0,14.0,140000284.0,1.0,1.400000e+12,Middleclass,Elderly,-71.000000,3.0,7.000000,...,-9.0,5.0,5.0,0.0,0.0,0.0,91.688043,-9.0,-9.0,-9.0
14000029101,18.0,18.0,140000291.0,1.0,1.400000e+12,Rich,Adult,138.333333,2.0,4.333333,...,-9.0,2.0,5.0,1.0,0.0,0.0,88.698225,-9.0,-9.0,-9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18025693601,126856.0,126856.0,180256936.0,1.0,1.800000e+12,Rich,Adult,-2.000000,3.0,4.800000,...,2.0,3.0,5.0,0.0,0.0,0.0,101.000000,0.0,1.0,1.0
18025694001,126861.0,126861.0,180256940.0,1.0,1.800000e+12,Rich,Elderly,-31.000000,3.0,4.400000,...,2.0,1.0,10.0,0.0,0.0,1.0,139.000000,0.0,0.0,0.0
18025694002,126866.0,126866.0,180256940.0,2.0,1.800000e+12,Rich,Elderly,91.000000,3.0,4.800000,...,2.0,1.0,10.0,0.0,0.0,1.0,139.000000,0.0,0.0,0.0
18025694101,126869.5,126869.5,180256941.0,1.0,1.800000e+12,Rich,Adult,-387.500000,1.5,2.500000,...,2.0,5.0,5.0,0.0,0.0,0.0,157.000000,0.0,1.0,0.0
18025694102,126872.0,126872.0,180256941.0,2.0,1.800000e+12,Rich,Adult,-165.000000,2.0,2.333333,...,2.0,5.0,5.0,0.0,0.0,0.0,157.000000,0.0,1.0,0.0

In [6]:

# locate and load file to Read 
df = pd.read_csv('semifinalHBO.csv')
df

,Unnamed: 0,PERSON_ID,O_PURPOSE_x,O_PURPOSE_y,Home_Based_Tour,Expected_Output
0,0,14000027101,HomeWorkStopStopWork,Home,HomeWorkStopStopWorkHome,True
1,1,14000027103,HomeStop,Home,HomeStopHome,False
2,2,14000028001,HomeWorkHomeStopStop,Home,HomeWorkHomeStopStopHome,True
3,3,14000029101,HomeWorkStop,Home,HomeWorkStopHome,True
4,4,14000029102,HomeStop,Home,HomeStopHome,False
...,...,...,...,...,...,...
31734,31734,18025693601,HomeStopHomeStopStop,Home,HomeStopHomeStopStopHome,False
31735,31735,18025694001,HomeStopStopStopStop,Home,HomeStopStopStopStopHome,False
31736,31736,18025694002,HomeStopStopHomeStop,Home,HomeStopStopHomeStopHome,False
31737,31737,18025694101,HomeStop,Home,HomeStopHome,False
31738,31738,18025694102,HomeWorkStop,Home,HomeWorkStopHome,True

In [7]:
dff=(pd.merge(df, aff, on='PERSON_ID'))
dff

,Unnamed: 0_x,PERSON_ID,O_PURPOSE_x,O_PURPOSE_y,Home_Based_Tour,Expected_Output,Unnamed: 0.1,Unnamed: 0_y,HOUSEHOLD_ID,PERSNO,...,MPO_HH_INCOME_BROAD,TDATE_DOW,HHTRIPS,PACKAGE_DELIVERED,FOOD_DELIVERED,SERVICE_DELIVERED,WTHHFIN,HOME_OWNERSHIP_IMP,HH_INCOME_DETAILED_IMP,NUMDISABILITIES_IMP
0,0,14000027101,HomeWorkStopStopWork,Home,HomeWorkStopStopWorkHome,True,2.0,2.0,140000271.0,1.0,...,-9.0,1.0,7.0,0.0,0.0,0.0,136.460113,-9.0,-9.0,-9.0
1,1,14000027103,HomeStop,Home,HomeStopHome,False,5.5,5.5,140000271.0,3.0,...,-9.0,1.0,7.0,0.0,0.0,0.0,136.460113,-9.0,-9.0,-9.0
2,2,14000028001,HomeWorkHomeStopStop,Home,HomeWorkHomeStopStopHome,True,9.0,9.0,140000280.0,1.0,...,-9.0,1.0,5.0,0.0,0.0,0.0,131.745870,-9.0,-9.0,-9.0
3,3,14000029101,HomeWorkStop,Home,HomeWorkStopHome,True,18.0,18.0,140000291.0,1.0,...,-9.0,2.0,5.0,1.0,0.0,0.0,88.698225,-9.0,-9.0,-9.0
4,4,14000029102,HomeStop,Home,HomeStopHome,False,20.5,20.5,140000291.0,2.0,...,-9.0,2.0,5.0,1.0,0.0,0.0,88.698225,-9.0,-9.0,-9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31734,31734,18025693601,HomeStopHomeStopStop,Home,HomeStopHomeStopStopHome,False,126856.0,126856.0,180256936.0,1.0,...,2.0,3.0,5.0,0.0,0.0,0.0,101.000000,0.0,1.0,1.0
31735,31735,18025694001,HomeStopStopStopStop,Home,HomeStopStopStopStopHome,False,126861.0,126861.0,180256940.0,1.0,...,2.0,1.0,10.0,0.0,0.0,1.0,139.000000,0.0,0.0,0.0
31736,31736,18025694002,HomeStopStopHomeStop,Home,HomeStopStopHomeStopHome,False,126866.0,126866.0,180256940.0,2.0,...,2.0,1.0,10.0,0.0,0.0,1.0,139.000000,0.0,0.0,0.0
31737,31737,18025694101,HomeStop,Home,HomeStopHome,False,126869.5,126869.5,180256941.0,1.0,...,2.0,5.0,5.0,0.0,0.0,0.0,157.000000,0.0,1.0,0.0
31738,31738,18025694102,HomeWorkStop,Home,HomeWorkStopHome,True,126872.0,126872.0,180256941.0,2.0,...,2.0,5.0,5.0,0.0,0.0,0.0,157.000000,0.0,1.0,0.0

In [8]:
dff=dff.applymap(str)
dff

,Unnamed: 0_x,PERSON_ID,O_PURPOSE_x,O_PURPOSE_y,Home_Based_Tour,Expected_Output,Unnamed: 0.1,Unnamed: 0_y,HOUSEHOLD_ID,PERSNO,...,MPO_HH_INCOME_BROAD,TDATE_DOW,HHTRIPS,PACKAGE_DELIVERED,FOOD_DELIVERED,SERVICE_DELIVERED,WTHHFIN,HOME_OWNERSHIP_IMP,HH_INCOME_DETAILED_IMP,NUMDISABILITIES_IMP
0,0,14000027101,HomeWorkStopStopWork,Home,HomeWorkStopStopWorkHome,True,2.0,2.0,140000271.0,1.0,...,-9.0,1.0,7.0,0.0,0.0,0.0,136.46011315,-9.0,-9.0,-9.0
1,1,14000027103,HomeStop,Home,HomeStopHome,False,5.5,5.5,140000271.0,3.0,...,-9.0,1.0,7.0,0.0,0.0,0.0,136.46011315,-9.0,-9.0,-9.0
2,2,14000028001,HomeWorkHomeStopStop,Home,HomeWorkHomeStopStopHome,True,9.0,9.0,140000280.0,1.0,...,-9.0,1.0,5.0,0.0,0.0,0.0,131.74586962,-9.0,-9.0,-9.0
3,3,14000029101,HomeWorkStop,Home,HomeWorkStopHome,True,18.0,18.0,140000291.0,1.0,...,-9.0,2.0,5.0,1.0,0.0,0.0,88.698225412,-9.0,-9.0,-9.0
4,4,14000029102,HomeStop,Home,HomeStopHome,False,20.5,20.5,140000291.0,2.0,...,-9.0,2.0,5.0,1.0,0.0,0.0,88.698225412,-9.0,-9.0,-9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31734,31734,18025693601,HomeStopHomeStopStop,Home,HomeStopHomeStopStopHome,False,126856.0,126856.0,180256936.0,1.0,...,2.0,3.0,5.0,0.0,0.0,0.0,101.0,0.0,1.0,1.0
31735,31735,18025694001,HomeStopStopStopStop,Home,HomeStopStopStopStopHome,False,126861.0,126861.0,180256940.0,1.0,...,2.0,1.0,10.0,0.0,0.0,1.0,139.0,0.0,0.0,0.0
31736,31736,18025694002,HomeStopStopHomeStop,Home,HomeStopStopHomeStopHome,False,126866.0,126866.0,180256940.0,2.0,...,2.0,1.0,10.0,0.0,0.0,1.0,139.0,0.0,0.0,0.0
31737,31737,18025694101,HomeStop,Home,HomeStopHome,False,126869.5,126869.5,180256941.0,1.0,...,2.0,5.0,5.0,0.0,0.0,0.0,157.0,0.0,1.0,0.0
31738,31738,18025694102,HomeWorkStop,Home,HomeWorkStopHome,True,126872.0,126872.0,180256941.0,2.0,...,2.0,5.0,5.0,0.0,0.0,0.0,157.0,0.0,1.0,0.0

#df1["WHYTO"].replace({1: 'Home', 2: 'Home', 3:'Stop', 4:'Stop', 5: 'Stop', 6:'Stop', 7:'Stop', 8:'Stop', 9:'Stop', 10:'Stop', 11:'Stop', 12:'Stop',13:'Stop',14:'Stop',15:'Stop',16:'Stop',17:'Stop',18:'Stop',19:'Stop',97:'Stop',-7 :'Stop', -8 : 'Stop', 97:'Stop',-9:'Stop'}, inplace=True)
#df1["D_PURPOSE"].replace({1: 'Home', 2: 'Work', 3:'Work', 4:'Shop', 7:'School', 8:'School', 9:'Other', 11:'Other',13:'Other',16:'Publictransit',17:'Publictransit',19:'Airport',77:'Other',99 :'Other',-9:'Other'}, inplace=True)
dff["RACEETHNICITY"].replace({1:"Hispanic", 2: "Black", 3:'Asian', 4:'White',5:'Others', -9:'Others'},  inplace = True)
#df["TRAVEL_MODE"].replace({1: 'Walk', 2: 'Bike', 3:'Bike', 4:'Car', 5:'Car', 6:'School bus', 7:'rail', 8:'Bus', 9:'Bus',10:'Para transit',11:'Taxi',12:'Taxi',13:'Air',14:'Water',15:'Others'}, inplace=True)
dff["TRAVEL_MODE"].replace({1: 'Walk', 2: 'Bike', 3:'Bike', 4:'Private car', 5:'Private car', 6:'School bus', 7:'Public transit', 8:'Public transit', 9:'Rideshare/Private Bus',10:'Rideshare/Private Bus',11:'Rideshare/Private Bus',12:'Rideshare/Private Bus',13:'Others',14:'Others',15:'Others'}, inplace=True)
#dff["D_PURPOSE"].replace({1: 'Home', 2: 'Stop', 3:'Stop', 4:'Stop', 7:'Stop', 8:'Stop', 9:'Stop', 11:'Stop',13:'Stop',16:'Stop',17:'Stop',18:'Stop',19:'Stop',77:'Stop',99 :'Stop',-9:'Stop'}, inplace=True)
dff

#home based work trips 
df1=dff.loc[dff.Goingtowork=='True', :]
df1.head(30)

# Home based work trips

In [9]:
#home based Other trips 
df1=dff.loc[dff.Expected_Output=='True', :]
df1

,Unnamed: 0_x,PERSON_ID,O_PURPOSE_x,O_PURPOSE_y,Home_Based_Tour,Expected_Output,Unnamed: 0.1,Unnamed: 0_y,HOUSEHOLD_ID,PERSNO,...,MPO_HH_INCOME_BROAD,TDATE_DOW,HHTRIPS,PACKAGE_DELIVERED,FOOD_DELIVERED,SERVICE_DELIVERED,WTHHFIN,HOME_OWNERSHIP_IMP,HH_INCOME_DETAILED_IMP,NUMDISABILITIES_IMP
0,0,14000027101,HomeWorkStopStopWork,Home,HomeWorkStopStopWorkHome,True,2.0,2.0,140000271.0,1.0,...,-9.0,1.0,7.0,0.0,0.0,0.0,136.46011315,-9.0,-9.0,-9.0
2,2,14000028001,HomeWorkHomeStopStop,Home,HomeWorkHomeStopStopHome,True,9.0,9.0,140000280.0,1.0,...,-9.0,1.0,5.0,0.0,0.0,0.0,131.74586962,-9.0,-9.0,-9.0
3,3,14000029101,HomeWorkStop,Home,HomeWorkStopHome,True,18.0,18.0,140000291.0,1.0,...,-9.0,2.0,5.0,1.0,0.0,0.0,88.698225412,-9.0,-9.0,-9.0
7,7,14000031601,HomeWorkHomeStopHome,Home,HomeWorkHomeStopHomeHome,True,38.0,38.0,140000316.0,1.0,...,-9.0,3.0,13.0,0.0,0.0,0.0,58.049674115,-9.0,-9.0,-9.0
8,8,14000031602,HomeWorkWorkWorkWorkWorkHomeStop,Home,HomeWorkWorkWorkWorkWorkHomeStopHome,True,44.5,44.5,140000316.0,2.0,...,-9.0,3.0,13.0,0.0,0.0,0.0,58.049674115,-9.0,-9.0,-9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31728,31728,18025682902,HomeStopWorkStop,Home,HomeStopWorkStopHome,True,126828.5,126828.5,180256829.0,2.0,...,2.0,2.0,8.0,0.0,0.0,0.0,245.0,0.0,0.0,0.0
31730,31730,18025684801,HomeWorkWorkWorkHomeStop,Home,HomeWorkWorkWorkHomeStopHome,True,126835.5,126835.5,180256848.0,1.0,...,2.0,2.0,6.0,0.0,0.0,0.0,95.0,0.0,0.0,0.0
31731,31731,18025686801,HomeWork,Home,HomeWorkHome,True,126839.5,126839.5,180256868.0,1.0,...,2.0,2.0,4.0,1.0,0.0,0.0,99.0,0.0,0.0,0.0
31732,31732,18025686802,HomeWork,Home,HomeWorkHome,True,126841.5,126841.5,180256868.0,2.0,...,2.0,2.0,4.0,1.0,0.0,0.0,99.0,0.0,0.0,0.0
31738,31738,18025694102,HomeWorkStop,Home,HomeWorkStopHome,True,126872.0,126872.0,180256941.0,2.0,...,2.0,5.0,5.0,0.0,0.0,0.0,157.0,0.0,1.0,0.0

In [52]:
df2=df1.loc[df1.Home_Based_Tour=='HomeWorkHome', :]
#df2=df1.loc[df1.Home_Based_Tour=='HomeWorkStopHome', :]
#df2=df1.loc[df1.Home_Based_Tour=='HomeWorkHomeStopHome', :]
#df2=df1.loc[df1.Home_Based_Tour=='HomeWorkStopWorkHome', :]
#df2=df1.loc[df1.Home_Based_Tour=='HomeWorkStopStopHome', :]
#df2=df1.loc[df1.Home_Based_Tour=='HomeStopWorkHome', :]
#df2=df1.loc[df1.Home_Based_Tour=='HomeStopWorkStopHome', :]
#df2=df1.loc[df1.Home_Based_Tour=='HomeWorkStopWorkStopHome', :]


#df2=df1.loc[df1.Home_Based_Tour=='HomeWorkHomeStopHome', :]

#df2=df1.loc[df1.Home_Based_Tour=='HomeWorkStopWorkHome', :]
df2

,Unnamed: 0_x,PERSON_ID,O_PURPOSE_x,O_PURPOSE_y,Home_Based_Tour,Expected_Output,Unnamed: 0.1,Unnamed: 0_y,HOUSEHOLD_ID,PERSNO,...,MPO_HH_INCOME_BROAD,TDATE_DOW,HHTRIPS,PACKAGE_DELIVERED,FOOD_DELIVERED,SERVICE_DELIVERED,WTHHFIN,HOME_OWNERSHIP_IMP,HH_INCOME_DETAILED_IMP,NUMDISABILITIES_IMP
12,12,14000032602,HomeWork,Home,HomeWorkHome,True,63.5,63.5,140000326.0,2.0,...,-9.0,5.0,23.0,0.0,0.0,0.0,164.78113545,-9.0,-9.0,-9.0
22,22,14000035403,HomeWork,Home,HomeWorkHome,True,109.5,109.5,140000354.0,3.0,...,-9.0,5.0,9.0,1.0,0.0,0.0,92.126939551,-9.0,-9.0,-9.0
32,32,14000036902,HomeWork,Home,HomeWorkHome,True,161.5,161.5,140000369.0,2.0,...,-9.0,3.0,10.0,1.0,0.0,0.0,64.580678902,-9.0,-9.0,-9.0
48,48,14000043501,HomeWork,Home,HomeWorkHome,True,257.5,257.5,140000435.0,1.0,...,-9.0,3.0,3.0,0.0,0.0,0.0,49.707068196,-9.0,-9.0,-9.0
60,60,14000052302,HomeWork,Home,HomeWorkHome,True,316.5,316.5,140000523.0,2.0,...,-9.0,4.0,6.0,1.0,0.0,0.0,81.130041015,-9.0,-9.0,-9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31720,31720,18025676701,HomeWork,Home,HomeWorkHome,True,126797.5,126797.5,180256767.0,1.0,...,2.0,5.0,2.0,0.0,0.0,0.0,52.0,0.0,0.0,0.0
31723,31723,18025679701,HomeWork,Home,HomeWorkHome,True,126806.5,126806.5,180256797.0,1.0,...,-9.0,1.0,2.0,0.0,0.0,0.0,50.871756134,0.0,0.0,0.0
31727,31727,18025682901,HomeWork,Home,HomeWorkHome,True,126825.5,126825.5,180256829.0,1.0,...,2.0,2.0,8.0,0.0,0.0,0.0,245.0,0.0,0.0,0.0
31731,31731,18025686801,HomeWork,Home,HomeWorkHome,True,126839.5,126839.5,180256868.0,1.0,...,2.0,2.0,4.0,1.0,0.0,0.0,99.0,0.0,0.0,0.0
31732,31732,18025686802,HomeWork,Home,HomeWorkHome,True,126841.5,126841.5,180256868.0,2.0,...,2.0,2.0,4.0,1.0,0.0,0.0,99.0,0.0,0.0,0.0

In [53]:
#analyzing Home Based WOrk trips 
df11=df2['RACEETHNICITY'].value_counts(normalize=True) * 100
df11

White       67.267771
Black       13.671629
Asian        9.834347
Hispanic     6.018033
Others       3.208220
Name: RACEETHNICITY, dtype: float64

In [54]:
#df11.to_csv('HBW tour.csv')

In [55]:
#analyzing Home Based WOrk trips 
df111=df2['RACEETHNICITY'].value_counts(normalize=True) * 100
df111

White       67.267771
Black       13.671629
Asian        9.834347
Hispanic     6.018033
Others       3.208220
Name: RACEETHNICITY, dtype: float64

In [56]:
#analyzing Home Based WOrk trips 
#df112=df1['TRAVEL_MODE'].value_counts(normalize=True) * 100
#df112
#analyzing Home Based WOrk trips 
df112=df2['Incomeclass'].value_counts(normalize=True) * 100
df112

Rich           65.506395
Middleclass    32.040260
Poverty         2.453345
Name: Incomeclass, dtype: float64

In [57]:
#analyzing Home Based WOrk trips 
df113=df2['GENDER'].value_counts(normalize=True) * 100
df113

Male      53.533235
Female    46.466765
Name: GENDER, dtype: float64

In [58]:
#analyzing Home Based WOrk trips 
df114=df2['LICENSE'].value_counts(normalize=True) * 100
df114

With License    95.302999
No License       4.697001
Name: LICENSE, dtype: float64

In [59]:
#analyzing Home Based WOrk trips 
df115=df2['DISABILITY'].value_counts(normalize=True) * 100
df115

Not disabled    98.154749
Disabled         1.719438
No response      0.125813
Name: DISABILITY, dtype: float64

In [60]:
#analyzing Home Based WOrk trips 
df116=df2['EMPLOYMENT_STATUS'].value_counts(normalize=True) * 100
df116

Employed      97.819249
Unemployed     0.985532
Retired        0.775844
Student        0.419375
Name: EMPLOYMENT_STATUS, dtype: float64

In [61]:

#analyzing Home Based WOrk trips 
df117=df2['Ageclass'].value_counts(normalize=True) * 100
df117

Adult           93.856154
Elderly          5.556720
Child            0.461313
Toddler/baby     0.083875
nan              0.041938
Name: Ageclass, dtype: float64


# Home based other tour

In [145]:
#home based Other trips 
df2=dff.loc[dff.Expected_Output=='False', :]
df2

,Unnamed: 0_x,PERSON_ID,O_PURPOSE_x,O_PURPOSE_y,Home_Based_Tour,Expected_Output,Unnamed: 0.1,Unnamed: 0_y,HOUSEHOLD_ID,PERSNO,...,MPO_HH_INCOME_BROAD,TDATE_DOW,HHTRIPS,PACKAGE_DELIVERED,FOOD_DELIVERED,SERVICE_DELIVERED,WTHHFIN,HOME_OWNERSHIP_IMP,HH_INCOME_DETAILED_IMP,NUMDISABILITIES_IMP
1,1,14000027103,HomeStop,Home,HomeStopHome,False,5.5,5.5,140000271.0,3.0,...,-9.0,1.0,7.0,0.0,0.0,0.0,136.46011315,-9.0,-9.0,-9.0
4,4,14000029102,HomeStop,Home,HomeStopHome,False,20.5,20.5,140000291.0,2.0,...,-9.0,2.0,5.0,1.0,0.0,0.0,88.698225412,-9.0,-9.0,-9.0
5,5,14000029901,HomeStop,Home,HomeStopHome,False,22.5,22.5,140000299.0,1.0,...,-9.0,4.0,2.0,0.0,0.0,0.0,58.049674115,-9.0,-9.0,-9.0
6,6,14000030901,HomeStopHomeStopStopStopStopStopStopStopStopStop,Home,HomeStopHomeStopStopStopStopStopStopStopStopSt...,False,29.5,29.5,140000309.0,1.0,...,-9.0,3.0,12.0,0.0,0.0,0.0,46.435774702,-9.0,-9.0,-9.0
9,9,14000032401,HomeStopStopStop,Home,HomeStopStopStopHome,False,50.5,50.5,140000324.0,1.0,...,-9.0,2.0,6.0,1.0,0.0,1.0,88.698225412,-9.0,1.0,-9.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
31733,31733,18025687501,HomeStopStopStopStopHomeStopStopStopStopStop,Home,HomeStopStopStopStopHomeStopStopStopStopStopHome,False,126848.0,126848.0,180256875.0,1.0,...,-9.0,3.0,11.0,0.0,0.0,0.0,36.146854639,0.0,1.0,0.0
31734,31734,18025693601,HomeStopHomeStopStop,Home,HomeStopHomeStopStopHome,False,126856.0,126856.0,180256936.0,1.0,...,2.0,3.0,5.0,0.0,0.0,0.0,101.0,0.0,1.0,1.0
31735,31735,18025694001,HomeStopStopStopStop,Home,HomeStopStopStopStopHome,False,126861.0,126861.0,180256940.0,1.0,...,2.0,1.0,10.0,0.0,0.0,1.0,139.0,0.0,0.0,0.0
31736,31736,18025694002,HomeStopStopHomeStop,Home,HomeStopStopHomeStopHome,False,126866.0,126866.0,180256940.0,2.0,...,2.0,1.0,10.0,0.0,0.0,1.0,139.0,0.0,0.0,0.0
31737,31737,18025694101,HomeStop,Home,HomeStopHome,False,126869.5,126869.5,180256941.0,1.0,...,2.0,5.0,5.0,0.0,0.0,0.0,157.0,0.0,1.0,0.0

In [146]:

df226=df2['Incomeclass'].value_counts(normalize=True) * 100
df226

Rich           59.217910
Middleclass    35.223581
Poverty         5.558509
Name: Incomeclass, dtype: float64

In [147]:
#analyzing Home Based WOrk trips 
df225=df2['RACEETHNICITY'].value_counts(normalize=True) * 100
df225

White       69.318920
Black       13.527084
Asian        7.661409
Others       5.068226
Hispanic     4.424361
Name: RACEETHNICITY, dtype: float64

In [148]:
#analyzing Home Based WOrk trips 
#df226=df2['TRAVEL_MODE'].value_counts(normalize=True) * 100
#df226

In [149]:
#analyzing Home Based WOrk trips 
df221=df2['GENDER'].value_counts(normalize=True) * 100
df221

Female         54.220568
Male           45.761711
No response     0.017721
Name: GENDER, dtype: float64

In [150]:
#analyzing Home Based WOrk trips 
df222=df2['LICENSE'].value_counts(normalize=True) * 100
df222

With License    65.467541
No License      34.337527
No response      0.194932
Name: LICENSE, dtype: float64

In [151]:
#analyzing Home Based WOrk trips 
df223=df2['DISABILITY'].value_counts(normalize=True) * 100
df223

Not disabled    86.626499
No response      9.079095
Disabled         4.294406
Name: DISABILITY, dtype: float64

In [152]:
#analyzing Home Based WOrk trips 
df224=df2['EMPLOYMENT_STATUS'].value_counts(normalize=True) * 100
df224

Unemployed    34.851438
Employed      32.766259
Retired       27.355426
Student        5.026877
Name: EMPLOYMENT_STATUS, dtype: float64

In [153]:

#analyzing Home Based WOrk trips 
df227=df2['Ageclass'].value_counts(normalize=True) * 100
df227

Adult           43.587926
Elderly         24.862662
Child           20.432394
Toddler/baby     9.947427
nan              1.169591
Name: Ageclass, dtype: float64

In [154]:
#analyzing Home Based WOrk trips 
df22=df2['Home_Based_Tour'].value_counts(normalize=True) * 100
df22

HomeStopHome                                                        36.351822
HomeStopStopHome                                                    14.430858
HomeStopHomeStopHome                                                 9.965149
HomeStopStopStopHome                                                 8.133971
HomeStopStopStopStopHome                                             3.715518
                                                                      ...
HomeStopStopStopStopStopHomeStopHomeStopHomeStopHome                 0.005907
HomeStopHomeStopStopHomeStopStopStopStopStopStopStopHome             0.005907
HomeStopStopHomeStopStopStopHomeHome                                 0.005907
HomeHomeStopStopStopStopStopHome                                     0.005907
HomeStopHomeStopHomeStopStopStopStopStopHomeStopHomeStopStopHome     0.005907
Name: Home_Based_Tour, Length: 281, dtype: float64

In [155]:

#df22.to_csv('HBO tour.csv')

In [39]:
#analyzing Home Based WOrk trips 
df11=df1['Home_Based_Tour'].value_counts(normalize=True) * 100
df11

HomeWorkHome                                                    32.201215
HomeWorkStopHome                                                11.796084
HomeWorkHomeStopHome                                             6.164754
HomeWorkStopWorkHome                                             4.037812
HomeWorkStopStopHome                                             3.490885
                                                                  ...
HomeStopStopStopHomeStopWorkStopWorkStopStopStopStopHome         0.006752
HomeStopStopStopHomeStopHomeStopHomeStopHomeWorkHomeStopHome     0.006752
HomeStopHomeStopWorkStopWorkHomeStopHome                         0.006752
HomeWorkWorkStopStopWorkHomeStopStopHome                         0.006752
HomeWorkWorkWorkWorkStopWorkStopWorkWorkHome                     0.006752
Name: Home_Based_Tour, Length: 880, dtype: float64

In [25]:


#af1=pd.concat([df1, af], axis=1, join='inner')